spring:
  datasource:
    username:
    password:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        wall:
          config:
            multi-statement-allow: true
  data:
    redis:
      host:
      username:
      password:
    mongodb:
      database: video
      uri:
      password:
  application:
    name: video-service
  cloud:
    nacos:
      server-addr: localhost:8848
      username:
      password:
logging:
  level:
    sql: trace
    web: trace
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: pers.cherish.videoservice

variable:
  redis:
    video-counter-key: counter:video
    video-comment-counter-key: counter:video:comment
    video-like-key-prefix: 'video:like:'
    video-dislike-key-prefix: 'video:dislike:'
    video-collect-key-prefix: 'video:collect:'
  page:
    video-page-size: 10
    video-like-page-size: 20
    video-collect-page-size: 20
  exclude-token-path: "/swagger-ui.html,/swagger-resources/**,
  /webjars/**,/swagger-ui/*,/v3/**,/video/*,/video/my/*,/video/search/*"
  public-path: "/user/login,/user"

cos:
  secret-id:
  secret-key:
  region:
  profile-bucket:
  videoBucket:
aspect:
  type: user

server:
  port: 8082