server:
  port: 8090
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username:
      password:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/video/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment/**
        - id: material-service
          uri: lb://material-service
          predicates:
            - Path=/material/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: true
            allowCredentials: true
      enabled: true
  application:
    name: gateway
logging:
  level:
    web: trace
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: gateway

