server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1h2sd2afhryr97eso.mysql.rds.aliyuncs.com/projsfv_user?&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: cherish
    password: Yuchenyu1
    druid:
      filter:
        wall:
          config:
            multi-statement-allow: true
  data:
    redis:
      host: r-uf62pi4o5awjt6sbqupd.redis.rds.aliyuncs.com
      username: cherish
      password: Yuchenyu1
    mongodb:
      uri: mongodb+srv://cherish:Yuchenyu1@cluster0.pa95kl8.mongodb.net/test
      password: Yuchenyu1
      database: user

  rabbitmq:
    virtual-host: /
    host: 123.249.7.164
    password: root
    username: root

  application:
    name: user-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: 893494ycy.

logging:
  level:
    web: trace
    sql: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pers.cherish.userservice
cos:
  secret-id: AKIDzrcEgv68C3iDWcZLvKXflkW5RfocIl15
  secret-key: tXyBAwUrY2JQl4BB1hASZSBjw2ykPtMi
  region: ap-nanjing
  profile-bucket: user-profile-1308753508

variable:
  page:
    friend-page-size: 10
    fans-page-size: 10
    blocked-page-size: 10
  user-counter-key: 'counter:user'
  salt: 'cherish'
  token-expire-time: 168
  public-path: "/user/login,/user"
  exclude-token-path: "/user,/swagger-ui.html,/swagger-resources/**,
  /webjars/**,/user/login,/swagger-ui/*,/v3/**,/user/*"
  rabbit:
    user-friend-exchange-key: 'user.friend.exchange'
    user-exchange-key: "user.exchange"
    user-fan&follow-exchange-key: 'user.fan.exchange'
    user-friend-routing-key-prefix: 'user.friends.'
    user-fan-routing-key-prefix: 'user.fans.'
    user-follow-routing-key-prefix: 'user.follows.'
    user-register-routing-key: 'user.register'
    user-update-routing-key: 'user.update'
  im:
    expire-time: 86400 # 单位s
aspect:
  type: user

im:
  sdkappid: 1400795083
  key: 1ce369a7348fb9071d7bc5c31ad988e37874b71c381ad67e687f28a06f2126b5
