server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1h2sd2afhryr97eso.mysql.rds.aliyuncs.com/projsfv_user?&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: cherish
    password: Yuchenyu1
    druid:
      filter:
        wall:
          config:
            multi-statement-allow: true
  data:
    redis:
      host:
      username:
      password:
    mongodb:
      uri:
      password:
      database:

  rabbitmq:
    virtual-host: /
    host:
    password:
    username:

  application:
    name: user-service
  cloud:
    nacos:
      username:
      password: .
      server-addr: 127.0.0.1:8848

logging:
  level:
    web: trace
    sql: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pers.cherish.userservice
cos:
  secret-id:
  secret-key:
  region: a
  profile-bucket:

variable:
  page:
    friend-page-size: 10
    fans-page-size: 10
    blocked-page-size: 10
  user-counter-key: 'counter:user'
  salt: 'cherish'
  token-expire-time: 168
  public-path: "/user/login,/user"
  exclude-token-path: "/user,/swagger-ui.html,/swagger-resources/**,
  /webjars/**,/user/login,/swagger-ui/*,/v3/**,/user/*"
  rabbit:
    user-friend-exchange-key: 'user.friend.exchange'
    user-exchange-key: "user.exchange"
    user-fan&follow-exchange-key: 'user.fan.exchange'
    user-friend-routing-key-prefix: 'user.friends.'
    user-fan-routing-key-prefix: 'user.fans.'
    user-follow-routing-key-prefix: 'user.follows.'
    user-register-routing-key: 'user.register'
    user-update-routing-key: 'user.update'
  im:
    expire-time: 86400 # 单位s
aspect:
  type: user

im:
  sdkappid:
  key:
