server:
  port: 8086
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    type: com.alibaba.druid.pool.DruidDataSource
    username:
    password:
    druid:
      filter:
        wall:
          config:
            multi-statement-allow: true
  application:
    name: material-service
  cloud:
    nacos:
      server-addr:
      username:
      password:
      discovery:
        ip:
  servlet:
    multipart:
      enabled: true
      max-file-size: 400000000
      max-request-size: 400000000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
cos:
  secret-id:
  secret-key:
  region: ap-nanjing
  profile-bucket:
  material-bucket:

logging:
  level:
    sql: trace
    web: trace