spring:
  datasource:
    username: cherish
    password: Yuchenyu1
    url: jdbc:mysql://rm-bp1h2sd2afhryr97eso.mysql.rds.aliyuncs.com/projsfv_comment?&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        wall:
          config:
            multi-statement-allow: true
  data:
    redis:
      host: r-uf62pi4o5awjt6sbqupd.redis.rds.aliyuncs.com
      username: cherish
      password: Yuchenyu1
  cloud:
    nacos:
      server-addr: localhost:8848
  application:
    name: comment-service
logging:
  level:
    sql: trace
    web: trace
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pers.cherish.videoservice

cos:
  secret-id: AKIDzrcEgv68C3iDWcZLvKXflkW5RfocIl15
  secret-key: tXyBAwUrY2JQl4BB1hASZSBjw2ykPtMi
  region: ap-nanjing
  profile-bucket: user-profile-1308753508
  videoBucket: video-1308753508

aspect:
  type: user

variable:
  redis:
    comment-counter-key-prefix: 'counter:comment:'
  page:
    parent-comment-size: 20
    child-comment-size: 5
server:
  port: 8081