spring:
  datasource:
    username:
    password:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        wall:
          config:
            multi-statement-allow: true
  data:
    redis:
      host:
      username:
      password:
  cloud:
    nacos:
      server-addr: localhost:8848
      username:
      password:
  application:
    name: comment-service
logging:
  level:
    sql: trace
    web: trace
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pers.cherish.videoservice

cos:
  secret-id:
  secret-key:
  region:
  profile-bucket:
  videoBucket:

aspect:
  type: user

variable:
  redis:
    comment-counter-key-prefix: 'counter:comment:'
    comment-like-key-prefix: 'comment:like:'
    comment-dislike-key-prefix: 'comment:dislike'
  page:
    parent-comment-size: 20
    child-comment-size: 5
server:
  port: 8081