server:
  port: 8084
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1
  application:
    name: recommend-service
  rabbitmq:
    addresses: 123.249.7.164
    virtual-host: /
    username: root
    password: root
  data:
    redis:
      host: r-uf62pi4o5awjt6sbqupd.redis.rds.aliyuncs.com
      username: cherish
      password: Yuchenyu1
    mongodb:
      uri: mongodb+srv://cherish:Yuchenyu1@cluster0.pa95kl8.mongodb.net/test
      password: Yuchenyu1
      database: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1h2sd2afhryr97eso.mysql.rds.aliyuncs.com/projsfv_user
    type: com.alibaba.druid.pool.DruidDataSource
    username: cherish
    password: Yuchenyu1