server:
  port: 8084
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1
  application:
    name: recommend-service
  rabbitmq:
    addresses:
    virtual-host: /
    username:
    password:
  data:
    redis:
      host:
      username:
      password:
    mongodb:
      uri:
      password:
      database:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    type: com.alibaba.druid.pool.DruidDataSource
    username:
    password: